# Databricks notebook source
# MAGIC %pip install mlflow langchain==0.2.16 langchain-community==0.2.17 langchain-core==0.2.41 databricks-sdk requests
# MAGIC dbutils.library.restartPython()
# MAGIC

# COMMAND ----------

"""
tests/test.py — Quality Gate for CI/CD Pipeline
Runs golden_set against the LangChain Multi–Genie-Space agent.
If accuracy < 80%, exits with sys.exit(1) to block deployment.
"""

import sys
import os
import importlib.util

# ── GET PROJECT ROOT ──────────────────────────────────────────────────────────
try:
    notebook_path = (
        dbutils.notebook.entry_point
        .getDbutils().notebook().getContext()
        .notebookPath().get()
    )
    project_root = "/Workspace/" + "/".join(notebook_path.strip("/").split("/")[:-2])
except Exception:
    project_root = "/Workspace/Users/sagarmeshram1729@gmail.com/databricks-cicd"

print(f"Project root: {project_root}")

# ── INJECT DATABRICKS CREDENTIALS AS ENV VARS ────────────────────────────────
# dbutils is available here in the notebook context, but NOT inside Python
# files loaded via importlib. So we extract the token/host NOW and set them
# as env vars so tools.py can read them.
try:
    ctx = dbutils.notebook.entry_point.getDbutils().notebook().getContext()
    token = ctx.apiToken().get()
    host  = ctx.apiUrl().get()
    os.environ["DATABRICKS_TOKEN"] = token
    os.environ["DATABRICKS_HOST"]  = host
    print(f"[test.py] ✅ Injected DATABRICKS_TOKEN + HOST from dbutils  host={host}")
except Exception as e:
    print(f"[test.py] ⚠️  Could not inject credentials from dbutils: {e}")

# Add project root to sys.path so `from agents.config import ...` works
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# ── LOAD AGENT MODULES (config → tools → agent) ──────────────────────────────
import types
agents_dir = os.path.join(project_root, "agents")

# Register 'agents' as a package so `from agents.config` works
if "agents" not in sys.modules:
    agents_pkg = types.ModuleType("agents")
    agents_pkg.__path__ = [agents_dir]
    sys.modules["agents"] = agents_pkg

# 1. Load config
config_path = os.path.join(agents_dir, "config.py")
config_spec = importlib.util.spec_from_file_location("agents.config", config_path)
config_mod = importlib.util.module_from_spec(config_spec)
sys.modules["agents.config"] = config_mod
config_spec.loader.exec_module(config_mod)

# 2. Load tools
tools_path = os.path.join(agents_dir, "tools.py")
tools_spec = importlib.util.spec_from_file_location("agents.tools", tools_path)
tools_mod = importlib.util.module_from_spec(tools_spec)
sys.modules["agents.tools"] = tools_mod
tools_spec.loader.exec_module(tools_mod)

# 3. Load main agent
agent_path = os.path.join(agents_dir, "mosaic_agent.py")
spec = importlib.util.spec_from_file_location("mosaic_agent", agent_path)
mosaic_agent = importlib.util.module_from_spec(spec)
sys.modules["mosaic_agent"] = mosaic_agent
spec.loader.exec_module(mosaic_agent)

predict = mosaic_agent.predict

# COMMAND ----------
# ── NOTE: Guardrails (validate_query_safety, validate_output_safety) run inside
# predict() and return structured results via result["security_gate"] / result["rai_gate"].
# No separate import needed here.

# COMMAND ----------

# ══════════════════════════════════════════════════════════════════════════════
#  CI GATE THRESHOLDS (Pipeline fails if ANY gate breaches its threshold)
# ══════════════════════════════════════════════════════════════════════════════
QUALITY_GATE_THRESHOLD   = 80.0    # Dual-gate accuracy must be >= 80%
SECURITY_GATE_THRESHOLD  = 100.0   # Security pass rate must be 100% (zero tolerance)
RAI_GATE_THRESHOLD       = 95.0    # RAI compliance must be >= 95%
COST_GATE_MAX_TOKENS     = 5000    # Average tokens per query must be <= 5000

# ── SQL LOGIC VALIDATION (Dual-Validation Gate) ──────────────────────────────
def validate_sql_logic(generated_sql, expected_keywords_string):
    """
    Simple, pragmatic SQL validation — the "Dual-Validation Gate".
    Converts everything to lowercase and checks for required keywords/tables.
    
    Prevents the "Right Answer, Wrong Math" problem where the AI hallucinates
    bad SQL that accidentally returns the correct number.
    
    Args:
        generated_sql: The SQL string generated by the Genie Space (can be None)
        expected_keywords_string: Comma-separated string of required keywords
                                  e.g. "fact_sale, sum, profit"
    Returns:
        (passed: bool, message: str)
    """
    # If no expected keywords defined for this row, skip validation
    if not expected_keywords_string or str(expected_keywords_string).strip() in ("", "nan", "None"):
        return True, "No keywords defined — skipped SQL logic check"
    
    # If we couldn't extract the generated SQL (Genie didn't return it)
    if not generated_sql or generated_sql.strip() == "":
        return False, "No SQL was generated/extracted from Genie Space"
    
    sql_lower = generated_sql.lower()
    required_keywords = [k.strip().lower() for k in expected_keywords_string.split(',')]
    
    missing = []
    for keyword in required_keywords:
        if keyword not in sql_lower:
            missing.append(keyword)
    
    if missing:
        return False, f"Missing required logic/table: {missing}"
    
    return True, "Passed SQL Logic Gate"

def run_evaluation(dataset_name: str, df):
    """
    Runs predict() on every row against all 4 CI gates:
      Gate 1 — QUALITY:  Dual-validation (answer match + SQL logic)
      Gate 2 — SECURITY: SQL injection, DML/DDL, credential leak detection
      Gate 3 — RAI:      Toxicity, PII, response size, hallucination detection
      Gate 4 — COST:     Token usage per query
    
    Returns dict with all gate metrics for final evaluation.
    """
    rows      = df.collect()
    total     = len(rows)
    correct   = 0
    sql_logic_pass = 0
    sql_logic_checked = 0
    dual_gate_pass = 0
    
    # Structured gate tracking
    security_pass_count = 0
    rai_pass_count = 0
    total_tokens_used = 0
    all_security_flags = []
    all_rai_flags = []

    print(f"\n{'='*70}")
    print(f"  EVALUATING: {dataset_name}  ({total} questions)")
    print(f"  CI GATES: Quality | Security | RAI | Cost")
    print(f"{'='*70}\n")

    for i, row in enumerate(rows, 1):
        question = row.question
        expected = str(row.expected_answer).strip()

        result     = predict(question)
        agent_ans  = result["answer"]
        agent_str  = str(agent_ans).strip()
        source     = result.get("source_tool", "N/A")
        gen_sql    = result.get("generated_sql", None)
        tokens     = result.get("total_tokens", 0)
        total_tokens_used += tokens

        # ── Security Gate (from structured result) ──
        sec_gate = result.get("security_gate", {"passed": True, "score": 1.0, "flags": [], "details": ""})
        if sec_gate["passed"]:
            security_pass_count += 1
        else:
            all_security_flags.extend(sec_gate["flags"])

        # ── RAI Gate (from structured result) ──
        rai_gate = result.get("rai_gate", {"passed": True, "score": 1.0, "flags": [], "details": ""})
        if rai_gate["passed"]:
            rai_pass_count += 1
        else:
            all_rai_flags.extend(rai_gate["flags"])

        # ── Gate 1: Tolerant accuracy match ──
        try:
            answer_match = abs(float(agent_str) - float(expected)) < 0.01
        except (ValueError, TypeError):
            agent_norm    = agent_str.split(" ")[0].lower().strip()
            expected_norm = expected.split(" ")[0].lower().strip()
            answer_match = agent_norm == expected_norm

        # ── Gate 2: SQL Logic Validation ──
        expected_kw = getattr(row, "expected_keywords", None)
        sql_valid, sql_msg = validate_sql_logic(gen_sql, expected_kw)
        
        has_keywords = expected_kw and str(expected_kw).strip() not in ("", "nan", "None")
        if has_keywords:
            sql_logic_checked += 1
            if sql_valid:
                sql_logic_pass += 1

        # ── Dual-Validation Gate: BOTH must pass ──
        if answer_match and sql_valid:
            dual_gate_pass += 1
            quality_status = "✅"
        else:
            quality_status = "❌"

        if answer_match:
            correct += 1

        # ── Running accuracy ──
        running_acc = (dual_gate_pass / i) * 100

        # ── Per-question report ──
        sec_icon = "✅" if sec_gate["passed"] else "🚨"
        rai_icon = "✅" if rai_gate["passed"] else "⚠️"
        
        print(f"[{i:02d}/{total}] Quality:{quality_status} Security:{sec_icon} RAI:{rai_icon}")
        print(f"  Q         : {question}")
        print(f"  Expected  : {expected}")
        print(f"  Agent     : {agent_str}")
        print(f"  Tool      : {source}")
        print(f"  Answer OK : {'✅' if answer_match else '❌'}")
        print(f"  SQL Logic : {'✅' if sql_valid else '❌'} {sql_msg}")
        print(f"  Security  : score={sec_gate['score']:.1f} {sec_gate['details']}")
        print(f"  RAI       : score={rai_gate['score']:.1f} {rai_gate['details']}")
        print(f"  Tokens    : {tokens}")
        if gen_sql:
            print(f"  SQL       : {gen_sql[:100]}{'...' if len(gen_sql) > 100 else ''}")
        print(f"  📈 Running Accuracy (Dual): {dual_gate_pass}/{i} → {running_acc:.1f}%")
        print()

    # ── Calculate final metrics ───────────────────────────────────────────
    accuracy = (correct / total) * 100
    dual_accuracy = (dual_gate_pass / total) * 100
    sql_pass_rate = (sql_logic_pass / sql_logic_checked * 100) if sql_logic_checked > 0 else 100.0
    security_rate = (security_pass_count / total) * 100
    rai_rate = (rai_pass_count / total) * 100
    avg_tokens = total_tokens_used / total if total > 0 else 0
    
    print(f"{'='*70}")
    print(f"  {dataset_name} — CI GATE RESULTS:")
    print(f"    Answer Accuracy   : {correct}/{total}  →  {accuracy:.1f}%")
    print(f"    SQL Logic Pass    : {sql_logic_pass}/{sql_logic_checked}  →  {sql_pass_rate:.1f}%")
    print(f"    Dual-Gate Accuracy: {dual_gate_pass}/{total}  →  {dual_accuracy:.1f}%")
    print(f"    Security Pass     : {security_pass_count}/{total}  →  {security_rate:.1f}%")
    print(f"    RAI Compliance    : {rai_pass_count}/{total}  →  {rai_rate:.1f}%")
    print(f"    Avg Tokens/Query  : {avg_tokens:.0f}")
    if all_security_flags:
        print(f"    ⚠️  Security Flags: {all_security_flags[:10]}")
    if all_rai_flags:
        print(f"    ⚠️  RAI Flags     : {all_rai_flags[:10]}")
    print(f"{'='*70}\n")
    
    return {
        "dual_accuracy":   dual_accuracy,
        "security_rate":   security_rate,
        "rai_rate":        rai_rate,
        "avg_tokens":      avg_tokens,
        "answer_accuracy": accuracy,
        "sql_pass_rate":   sql_pass_rate,
        "security_flags":  all_security_flags,
        "rai_flags":       all_rai_flags,
    }

# COMMAND ----------

# ── GOLDEN SET ────────────────────────────────────────────────────────────────
# Load from repo CSV (NOT from Delta table) so that changes in eval/golden_set.csv
# are immediately reflected in the CI/CD quality gate.
import pandas as pd

golden_csv_path = os.path.join(project_root, "eval", "golden_set.csv")
print(f"[test.py] Loading golden set from: {golden_csv_path}")
golden_pdf = pd.read_csv(golden_csv_path)
print(f"[test.py] Golden set loaded: {len(golden_pdf)} questions")

# Convert to Spark DataFrame so run_evaluation() (which calls .collect()) works
golden_df  = spark.createDataFrame(golden_pdf.astype(str))
results    = run_evaluation("GOLDEN SET", golden_df)

# COMMAND ----------

# ══════════════════════════════════════════════════════════════════════════════
#  FINAL CI GATE EVALUATION — Pipeline blocks if ANY gate fails
# ══════════════════════════════════════════════════════════════════════════════

quality_pass  = results["dual_accuracy"]  >= QUALITY_GATE_THRESHOLD
security_pass = results["security_rate"]  >= SECURITY_GATE_THRESHOLD
rai_pass      = results["rai_rate"]       >= RAI_GATE_THRESHOLD
cost_pass     = results["avg_tokens"]     <= COST_GATE_MAX_TOKENS

all_gates_pass = quality_pass and security_pass and rai_pass and cost_pass

print("=" * 70)
print("  FINAL CI GATE SUMMARY")
print("=" * 70)
print(f"  Agent Type          : LangChain ReAct (Multi–Genie-Space)")
print(f"")
print(f"  ┌──────────────┬────────────┬────────────┬─────────┐")
print(f"  │ Gate         │ Score      │ Threshold  │ Status  │")
print(f"  ├──────────────┼────────────┼────────────┼─────────┤")
print(f"  │ Quality      │ {results['dual_accuracy']:>8.1f}%  │ {QUALITY_GATE_THRESHOLD:>8.1f}%  │ {'✅ PASS' if quality_pass else '❌ FAIL'}  │")
print(f"  │ Security     │ {results['security_rate']:>8.1f}%  │ {SECURITY_GATE_THRESHOLD:>8.1f}%  │ {'✅ PASS' if security_pass else '🚨 FAIL'}  │")
print(f"  │ RAI          │ {results['rai_rate']:>8.1f}%  │ {RAI_GATE_THRESHOLD:>8.1f}%  │ {'✅ PASS' if rai_pass else '⚠️ FAIL'}  │")
print(f"  │ Cost         │ {results['avg_tokens']:>7.0f} tk │ {COST_GATE_MAX_TOKENS:>7d} tk │ {'✅ PASS' if cost_pass else '💰 FAIL'}  │")
print(f"  └──────────────┴────────────┴────────────┴─────────┘")
print(f"")
print(f"  OVERALL: {'✅ ALL GATES PASSED' if all_gates_pass else '🚨 GATE FAILURE — DEPLOYMENT BLOCKED'}")
print("=" * 70)

# ── HARD GATE: block CI/CD deployment if ANY gate fails ───────────────────────
if not all_gates_pass:
    print(f"\n🚨 CI GATE FAILURE — Deployment blocked!")
    if not quality_pass:
        print(f"   ❌ QUALITY: {results['dual_accuracy']:.1f}% < {QUALITY_GATE_THRESHOLD}% threshold")
    if not security_pass:
        print(f"   🚨 SECURITY: {results['security_rate']:.1f}% < {SECURITY_GATE_THRESHOLD}% (ZERO TOLERANCE)")
        print(f"      Flags: {results['security_flags'][:5]}")
    if not rai_pass:
        print(f"   ⚠️  RAI: {results['rai_rate']:.1f}% < {RAI_GATE_THRESHOLD}% threshold")
        print(f"      Flags: {results['rai_flags'][:5]}")
    if not cost_pass:
        print(f"   💰 COST: {results['avg_tokens']:.0f} tokens/query > {COST_GATE_MAX_TOKENS} limit")
else:
    print(f"\n✅ All CI gates passed. Safe to deploy.")
    print(f"   Quality={results['dual_accuracy']:.1f}%  Security={results['security_rate']:.1f}%  RAI={results['rai_rate']:.1f}%  Cost={results['avg_tokens']:.0f}tk")

# ── Machine-readable output for GitHub Actions to parse ───────────────────────
# This line is grepped by the CI pipeline to extract scores for the step summary.
import json
gate_output = {
    "quality_score":    round(results["dual_accuracy"], 1),
    "quality_threshold": QUALITY_GATE_THRESHOLD,
    "quality_pass":     quality_pass,
    "security_score":   round(results["security_rate"], 1),
    "security_threshold": SECURITY_GATE_THRESHOLD,
    "security_pass":    security_pass,
    "rai_score":        round(results["rai_rate"], 1),
    "rai_threshold":    RAI_GATE_THRESHOLD,
    "rai_pass":         rai_pass,
    "cost_score":       round(results["avg_tokens"], 0),
    "cost_threshold":   COST_GATE_MAX_TOKENS,
    "cost_pass":        cost_pass,
    "answer_accuracy":  round(results["answer_accuracy"], 1),
    "sql_pass_rate":    round(results["sql_pass_rate"], 1),
    "overall_pass":     all_gates_pass,
    "security_flags":   results["security_flags"][:5],
    "rai_flags":        results["rai_flags"][:5],
}
print(f"CI_GATE_JSON:{json.dumps(gate_output)}")

# Now fail the job if needed so Databricks Bundle Run returns an exit code of 1
if not all_gates_pass:
    sys.exit(1)

